Fix a typo causing a traceback when undoing transactions
Before this commit, pressing the "undo" button in history view would always result in this traceback:

```
__init__.py:1123:on_history_undo:AttributeError: 'Window' object has no attribute 'process_actions'

Traceback (most recent call last):
  File "/path/to/yumex-dnf/src/yumex/__init__.py", line 1123, in on_history_undo
    self.process_actions(from_queue=False)
AttributeError: 'Window' object has no attribute 'process_actions'
```

Fixes rhbz #1336102.